# fly.toml app configuration file generated for apirestore on 2024-04-24T06:45:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apirestore'
primary_region = 'jnb'

[build]
  image = 'kgotsom/restore:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings_PublishableKey="pk_test_51P5gFwCiRwIcdtF4FLyFjZ8v1PYuVxRacxSVML2BVeGzpevVhYgvwI7sgejrUVZxLkHpmddFVbZgsYc0XPNKfKZs006hulLXQ5"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
